# Generated by Django 5.0.4 on 2024-05-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='longitude',
        ),
        migrations.AddField(
            model_name='soildata',
            name='battery',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soildata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soildata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='central',
            name='image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/004/261/672/original/green-seedling-planted-in-box-spring-natural-decorative-design-element-colorful-seasonal-illustration-in-flat-cartoon-style-vector.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='central',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='central',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/004/261/672/original/green-seedling-planted-in-box-spring-natural-decorative-design-element-colorful-seasonal-illustration-in-flat-cartoon-style-vector.jpg', max_length=150),
        ),
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
