# Generated by Django 5.0.4 on 2024-05-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='central',
            name='image',
            field=models.CharField(default='https://static.vecteezy.com/system/resources/previews/004/261/672/original/green-seedling-planted-in-box-spring-natural-decorative-design-element-colorful-seasonal-illustration-in-flat-cartoon-style-vector.jpg', max_length=150),
        ),
    ]
