# Generated by Django 5.0.4 on 2024-06-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_node_latitude_remove_node_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='sensor_id',
            field=models.IntegerField(default=1),
        ),
    ]
