# Generated by Django 5.0.4 on 2024-05-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_central_latitude_alter_central_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='node',
            name='longitude',
        ),
        migrations.AddField(
            model_name='soildata',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soildata',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
