# Generated by Django 5.0.4 on 2024-05-30 11:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_node_latitude_remove_node_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='soil_data_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
