# Generated by Django 5.0.4 on 2024-05-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_soildata_soil_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soildata',
            name='battery',
            field=models.FloatField(default=0.0),
        ),
    ]
